### ISSUE TITLE
Windows errors during testing

### ISSUE THREAD

**Issue by mikedotexe** [near/devx#101]
We have an issue on Windows for these examples:
https://github.com/near-examples/counter/pull/14
https://github.com/near-examples/wallet-example/pull/14

**Comment by mikedotexe** [comment]
Basically it's this:
```
C:\Users\mike\counter>yarn asp
yarn run v1.22.4
warning package.json: No license field
$ asp --verbose
       ___   _____                       __
      /   | / ___/      ____  ___  _____/ /_
     / /| | \__ \______/ __ \/ _ \/ ___/ __/
    / ___ |___/ /_____/ /_/ /  __/ /__/ /_
   /_/  |_/____/     / .___/\___/\___/\__/
                    /_/

⚡AS-pect⚡ Test suite runner [3.1.4]

[Log] Loading asc compiler
[Log] Compiler loaded in 295.254ms.
[Log] Using configuration C:\Users\mike\counter\as-pect.config.js
[Log] Using VerboseReporter
[Log] Including files: assembly/__tests__/**/*.spec.ts
[Log] Running tests that match: (:?)
[Log] Running groups that match: (:?)
[Log] Effective command line args:
  [TestFile.ts] node_modules\@as-pect\assembly\assembly\index.ts C:\Users\mike\counter\node_modules\near-sdk-as\assembly\vm\vm.include.ts --validate --debug --binaryFile output.wasm --runtime stub --baseDir C:\Users\mike\counter --runPasses inlining,dce --transform C:\Users\mike\counter\node_modules\near-sdk-as\bindgen,C:\Users\mike\counter\node_modules\@as-pect\core\lib\transform\index.js --explicitStart --use ASC_RTRACE=1 --exportTable --importMemory

[Error] There was a compilation error when trying to create the wasm binary for file: assembly/__tests__/main.spec.ts.
Error: Import 'outcome' not found.
    at parseBacklog (C:\Users\mike\counter\node_modules\assemblyscript\cli\asc.js:498:34)
    at Object.main (C:\Users\mike\counter\node_modules\assemblyscript\cli\asc.js:554:16)
    at C:\Users\mike\counter\node_modules\@as-pect\cli\lib\run.js:577:17
    at Array.forEach (<anonymous>)
    at run (C:\Users\mike\counter\node_modules\@as-pect\cli\lib\run.js:575:36)
    at Object.asp (C:\Users\mike\counter\node_modules\@as-pect\cli\lib\index.js:63:9)
    at Object.<anonymous> (C:\Users\mike\counter\node_modules\@as-pect\cli\bin\asp:2:28)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\mike\counter>
```
